### ISSUE TITLE
Adjusts

### ISSUE THREAD

**Issue by ktquez** [ktquez/pickout#15]

**Comment by ktquez** [comment]
- Modal Fixed
- Style input search in modal

``` css
/* Update to */

.pk-search > input {
    width: calc(100% - 22px)
}

.pk-modal > .main {
    margin:0;
}
```
